### ISSUE TITLE
Applicability for gitea

### ISSUE THREAD

**Issue by xaionaro** [facebookincubator/go-belt#29]
@6543 : Hey! I do not know if you remember, but we discussed a couple of years ago how a proper logger should look like. And the ideas I was pitching for are implemented in this repository. So I'm curious if you are interested in applying this `Logger` in gitea. I'll be happy to prepare a PR myself. I'm also happy to answer to any questions.

**Comment by 6543** [comment]
hi @xaionaro :wave: well "couple of years" rushed by in a blink :sweat_smile: 

> So I'm curious if you are interested in applying this Logger in gitea

let me look

**Comment by 6543** [comment]
from gitea maintainers side, they will focus on https://pkg.go.dev/golang.org/x/exp/slog asap it got merged to std-lib ... not sure if that's what you want to hear :D

**Comment by xaionaro** [comment]
> from gitea maintainers side, they will focus on https://pkg.go.dev/golang.org/x/exp/slog asap it got merged to std-lib ... not sure if that's what you want to hear :D

Well, it makes sense. Hopefully in the standard `slog` they will eventually add anything needed for usual developer experience.

Meanwhile I'll add support for `slog` in `go-belt` :)

**Comment by 6543** [comment]
well that will work too :)
